nama_lengkap = input("NAMA LENGKAP : ")
nisn         = input("NISN         : ")
kelas        = input("KELAS        : ")
no_absen     = input("NO ABSEN     : ")
jurusan      = input("JURUSAN      : ")
alamat       = input("Alamat       : ")
tinggi_badan = input("TINGGI BADAN : ")
berat_badan  = input("BERAT BADAN  : ")
hobi         = input("HOBI         : ")
telepon      = input("TELEPON      : ")

print("==============================================")
print("----BIODATA SISWA REKAYASA PERANGKAT LUNAK----")
print("==============================================")
print("NAMA LENGKAP       :", nama_lengkap)
print("NISN               :", nisn)
print("KELAS              :", kelas)
print("NO ABSEN           :", no_absen)
print("JURUSAN            :", jurusan)
print("Alamat             :", alamat)
print("TINGGI BADAN       :", tinggi_badan, "cm")
print("BERAT BADAN        :", berat_badan, "kg")
print("HOBI               :", hobi)
print("TELEPON            :", telepon)
print("------------------THANK YOU------------------")

